### ISSUE TITLE
demo.py TimeoutExpired error

### ISSUE THREAD

**Issue by robmarkcole** [open-homeautomation/miflora#20] opened 2017-03-18 09:55 UTC
When running demo.py

```
from subprocess import PIPE, Popen, TimeoutExpired

ImportError: cannot import name TimeoutExpired

```

**Comment by open-homeautomation** [comment] 2017-03-18 09:57
Most likely you're using Python2. This library requires Python3.

**Comment by micksel** [comment] 2017-04-24 12:29
I'm getting the same error on Python3, Raspbian/wheezy

**Comment by ChristianKuehnel** [comment] 2017-10-25 18:31
@robmarkcole 
Do you still have the issue with the current master branch?

**Comment by ChristianKuehnel** [comment] 2017-10-25 18:32
is this a duplicate of https://github.com/open-homeautomation/miflora/issues/29 ?

**Comment by ChristianKuehnel** [comment] 2017-11-27 08:23
should be fixed with https://github.com/open-homeautomation/miflora/pull/61

**Closed by ChristianKuehnel** 2017-11-27 08:23 UTC
